#!/bin/env bash
: "
Unit Tests
for tmuxctrl
"

SRC_DIR="../src"
SRC="tmuxctrl"
FLAGS=""

# Source Libraries
. unittests.sh

### ========= Panes ========== ###
test_pane_movements()
{
    # Test moving pane left
    cmd="$SRC_DIR/tmuxctrl p m -l"
    assertEquals "$cmd" "Move Left"

    # Test moving pane right
    cmd="$SRC_DIR/tmuxctrl p m -r"
    assertEquals "$cmd" "Move Right"

    # Test moving pane up
    cmd="$SRC_DIR/tmuxctrl p m -u"
    assertEquals "$cmd" "Move Up"

    # Test moving pane down
    cmd="$SRC_DIR/tmuxctrl p m -d"
    assertEquals "$cmd" "Move Down"
}

### ========= Sessions ========== ###
test_session_list()
{
    # Test list all sessions
    cmd="$SRC_DIR/tmuxctrl s -p"
    assertSuccess "$cmd"
}

### ========= Windows ========== ###
test_window_split()
{
    : "
    Split Window Panes 
    - Horizontal
    - Vertical
    "
    # List Panes
    tmux list-panes
}

main()
{
    argv=("$@")
    argc="${#argv[@]}"

    echo -e "========================="
    echo -e " Testing Session Options "
    echo -e "========================="
    test_session_list

    echo -e ""

    echo -e "========================"
    echo -e " Testing Pane Movements "
    echo -e "========================"
    test_pane_movements
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
